webtalk_init -webtalk_dir C:/Users/vcvin/Documents/MotherboardSampleProject/MotherboardSampleProject.sim/sim_1/behav/xsim/xsim.dir/tb_Motherboard_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 14 01:58:05 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "868983cd-ceb9-49c9-aa06-35d4f114b9c4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b4ccf4c568a74c77bf550aa8d74997fc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "56" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "990047 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.51_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "21644_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3058568193 -regid "" -xml C:/Users/vcvin/Documents/MotherboardSampleProject/MotherboardSampleProject.sim/sim_1/behav/xsim/xsim.dir/tb_Motherboard_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/vcvin/Documents/MotherboardSampleProject/MotherboardSampleProject.sim/sim_1/behav/xsim/xsim.dir/tb_Motherboard_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/vcvin/Documents/MotherboardSampleProject/MotherboardSampleProject.sim/sim_1/behav/xsim/xsim.dir/tb_Motherboard_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
